-- Biophilia Institute Initial Data Dump
-- This script populates the database with the initial content of the website.
-- Run this script only once after creating the schema with `schema.sql`.

-- Clear existing data to prevent duplicates on re-run during development
DELETE FROM project_activities;
DELETE FROM projects;
DELETE FROM team_members;
DELETE FROM blog_posts;
DELETE FROM pages_content;
DELETE FROM ui_text;
DELETE FROM global_content;

-- 1. GLOBAL CONTENT (Logo, Navigation, Footer, Social Links)
INSERT INTO `global_content` (`id`, `logoUrl`, `navigation`, `socialLinks`, `footer`) VALUES
(1, 'https://biophiliaweb.org/logo-biophilia.png', '[
  {"id": "nav_home", "to": "/", "label": {"en": "Home", "es": "Inicio"}, "end": true},
  {"id": "nav_about", "to": "/about", "label": {"en": "About Us", "es": "Nosotros"}},
  {"id": "nav_projects", "to": "/projects", "label": {"en": "Our Programs", "es": "Nuestros Programas"}},
  {"id": "nav_team", "to": "/team", "label": {"en": "Our Team", "es": "Nuestro Equipo"}},
  {"id": "nav_blog", "to": "/blog", "label": {"en": "Blog", "es": "Blog"}},
  {"id": "nav_contact", "to": "/contact", "label": {"en": "Contact", "es": "Contacto"}}
]', '[
  {"id": "facebook", "url": "https://www.facebook.com/BiophiliaInstitute/"},
  {"id": "instagram", "url": "https://www.instagram.com/biophiliainstitute/"},
  {"id": "linkedin", "url": "https://www.linkedin.com/company/biophilia-institute/"},
  {"id": "twitter", "url": "https://x.com/BiophiliaInst"}
]', '{
  "slogan": {"en": "Connecting humanity with nature: fostering a sustainable and resilient future for all.", "es": "Conectando la humanidad con la naturaleza: fomentando un futuro sostenible y resiliente para todos."},
  "copyright": {"en": "Biophilia Institute. All rights reserved.", "es": "Biophilia Institute. Todos los derechos reservados."},
  "contact": {
    "address": "Sanford, Florida.",
    "email": "admin@biophiliaweb.org"
  }
}');

-- 2. UI TEXT (Common button labels and interface texts)
INSERT INTO `ui_text` (`id`, `texts`) VALUES
(1, '{
  "donateNow": {"en": "Donate Now", "es": "Donar Ahora"},
  "supportMission": {"en": "Support Our Mission", "es": "Apoya Nuestra Misión"},
  "viewAllProjects": {"en": "View All Programs", "es": "Ver Todos los Programas"},
  "learnMore": {"en": "Learn More", "es": "Leer Más"},
  "readMore": {"en": "Read More", "es": "Leer Más"},
  "contact": {"en": "Contact", "es": "Contacto"},
  "viewActions": {"en": "See Actions", "es": "Ver Acciones"}
}');

-- 3. PAGES CONTENT (JSON blobs for each page)
-- 3.1 Home Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('homePage', '{
  "heroSlides": [
    {
      "id": "hero_main",
      "title": {"en": "Biophilia", "es": "Biophilia"},
      "subtitle": {"en": "Nature,\\nEducation,\\nConservation.", "es": "Naturaleza,\\nEducación,\\nConservación."},
      "imageUrl": "https://biophiliaweb.org/images/otros/Banner Biophilia2.jpg"
    },
    {
      "id": "hero_1",
      "title": {"en": "First tree of the Community Faith Forest project in Orlando, FL.", "es": "Primer árbol del proyecto Bosque Comunitario de la Fe, en Orlando. FL."},
      "subtitle": {"en": "More than 1000 trees will be planted, consolidating an urban ecological corridor.", "es": "Se plantarán más de 1000 árboles, y se consolidará un corredor ecológico urbano."},
      "imageUrl": "https://biophiliaweb.org/images/banners/Banner_1.jpeg",
      "projectId": "project_urban_forest",
      "activityId": "activity_urban_forest_1"
    },
    {
      "id": "hero_2",
      "title": {"en": "Papayas, seedlings and mental health in the Engelwood garden, in Orlando.", "es": "Papayas, semilleros y salud mental en el huerto de Engelwood, en Orlando."},
      "subtitle": {"en": "At least 14 seniors shared knowledge and experiences during the day.", "es": "Al menos 14 adultos mayores compartieron saberes y experiencias durante la jornada."},
      "imageUrl": "https://biophiliaweb.org/images/banners/Banner_2.jpeg",
      "projectId": "project_urban_harvest",
      "activityId": "activity_urban_harvest_2"
    },
    {
      "id": "hero_3",
      "title": {"en": "Sea turtle workshop teaches young people to protect our oceans.", "es": "Taller de tortugas marinas enseña a jóvenes a proteger nuestros océanos."},
      "subtitle": {"en": "32 young people from Orlando sensitized and received an ocean conservation kit.", "es": "32 jóvenes de Orlando sensibilizados y recibieron kit de conservación de océanos."},
      "imageUrl": "https://biophiliaweb.org/images/banners/Banner_3.jpeg",
      "projectId": "project_ocean_guardians",
      "activityId": "activity_ocean_guardians_1"
    },
    {
      "id": "hero_4",
      "title": {"en": "From branch to forest: science and community in Azalea Park, Orlando. FL.", "es": "De la rama al bosque: ciencia y comunidad en Azalea Park, Orlando. FL."},
      "subtitle": {"en": "30 young people learned to propagate trees from the branch, with air layering.", "es": "30 jóvenes aprendieron a propagar arboles desde la rama, con acodos aéreos."},
      "imageUrl": "https://biophiliaweb.org/images/otros/10.jpg",
      "projectId": "project_symbiosis",
      "activityId": "activity_symbiosis_1"
    }
  ],
  "welcome": {
    "titlePart1": {"en": "Welcome to", "es": "Bienvenido a"},
    "titlePart2": {"en": "Biophilia Institute", "es": "Biophilia Institute"},
    "slogan": {"en": "A commitment to life, a promise for the future.", "es": "Un compromiso con la vida, una promesa para el futuro."},
    "text": {"en": "We are a non-profit organization dedicated to strengthening the bond between humanity and nature. Through innovative educational programs, community conservation projects, and scientific research with purpose, we work to build resilient and sustainable communities where both people and ecosystems can thrive.", "es": "Somos una organización sin fines de lucro, dedicada a fortalecer el vínculo entre la humanidad y la naturaleza. A través de programas educativos innovadores, proyectos de conservación comunitarios y ciencia con propósito, trabajamos para construir comunidades resilientes y sostenibles, donde tanto las personas como los ecosistemas puedan prosperar."},
    "imageUrl": "https://biophiliaweb.org/images/proyectos/P1.jpeg",
    "imageAlt": "Community members planting a tree together."
  },
  "actionLines": {
    "title": {"en": "Thematic Areas", "es": "Áreas Temáticas"},
    "items": [
      { "id": "value_2", "title": {"en": "Connection with Nature", "es": "Conexión con la Naturaleza"}, "text": {"en": "We promote direct experiences in nature to strengthen the emotional and cognitive bond with our environment.", "es": "Promovemos experiencias directas en la naturaleza para fortalecer el vínculo emocional y cognitivo con nuestro entorno."}, "imageUrl": "https://biophiliaweb.org/images/valores/conexion.png"},
      { "id": "value_3", "title": {"en": "Transformative Education", "es": "Educación Transformadora"}, "text": {"en": "We design educational programs that inspire curiosity, critical thinking, and a lasting commitment to conservation.", "es": "Diseñamos programas educativos que inspiran la curiosidad, el pensamiento crítico y el compromiso duradero con la conservación."}, "imageUrl": "https://biophiliaweb.org/images/valores/eucation.png"},
      { "id": "value_6", "title": {"en": "Science with Purpose", "es": "Ciencia con Propósito"}, "text": {"en": "We apply scientific research to understand and address local environmental challenges, generating practical solutions.", "es": "Aplicamos la investigación científica para comprender y abordar los desafíos ambientales locales, generando soluciones prácticas."}, "imageUrl": "https://biophiliaweb.org/images/valores/science.png"},
      { "id": "value_4", "title": {"en": "Social Equity", "es": "Equidad Social"}, "text": {"en": "We work to ensure that all communities, especially the most vulnerable, have access to a healthy environment.", "es": "Trabajamos para que todas las comunidades, en especial las más vulnerables, tengan acceso a un medio ambiente sano."}, "imageUrl": "https://biophiliaweb.org/images/valores/social.png"},
      { "id": "value_5", "title": {"en": "Community Leadership", "es": "Liderazgo Comunitario"}, "text": {"en": "We empower local leaders and organizations to be protagonists in the conservation of their natural resources.", "es": "Empoderamos a líderes y organizaciones locales para que sean protagonistas en la conservación de sus recursos naturales."}, "imageUrl": "https://biophiliaweb.org/images/valores/liderazgo.png"},
      { "id": "value_1", "title": {"en": "Collaboration", "es": "Colaboración"}, "text": {"en": "We build alliances between communities, organizations, and governments to multiply the impact of our actions.", "es": "Construimos alianzas entre comunidades, organizaciones y gobiernos para multiplicar el impacto de nuestras acciones."}, "imageUrl": "https://biophiliaweb.org/images/valores/colaboracion.png"}
    ]
  },
  "latestProjects": {
    "title": {"en": "Our Programs", "es": "Nuestros Programas"},
    "slogan": {"en": "From the community, for the planet.", "es": "Desde la comunidad, para el planeta."},
    "subtitle": {"en": "Discover how our programs are generating a positive impact, from restoring urban forests to training the next generation of environmental leaders.", "es": "Descubre cómo nuestros programas están generando un impacto positivo, desde la restauración de bosques urbanos hasta la formación de la próxima generación de líderes ambientales."}
  },
  "parallax1": {
    "title": {"en": "Join the Change", "es": "Únete al Cambio"},
    "text": {"en": "Your support is essential to continue building a green and equitable future. Every contribution, big or small, helps us bring our programs to more communities.", "es": "Tu apoyo es fundamental para seguir construyendo un futuro verde y equitativo. Cada contribución, grande o pequeña, nos ayuda a llevar nuestros programas a más comunidades."},
    "imageUrl": "https://biophiliaweb.org/images/otros/Parallax_1.jpeg"
  },
  "values": {
    "title": {"en": "Our Values", "es": "Nuestros Valores"},
    "items": [
        { "id": "value_2", "title": {"en": "Connection with Nature", "es": "Conexión con la Naturaleza"}, "text": {"en": "We promote direct experiences in nature to strengthen the emotional and cognitive bond with our environment.", "es": "Promovemos experiencias directas en la naturaleza para fortalecer el vínculo emocional y cognitivo con nuestro entorno."}, "imageUrl": "https://biophiliaweb.org/images/valores/conexion.png"},
        { "id": "value_3", "title": {"en": "Transformative Education", "es": "Educación Transformadora"}, "text": {"en": "We design educational programs that inspire curiosity, critical thinking, and a lasting commitment to conservation.", "es": "Diseñamos programas educativos que inspiran la curiosidad, el pensamiento crítico y el compromiso duradero con la conservación."}, "imageUrl": "https://biophiliaweb.org/images/valores/eucation.png"},
        { "id": "value_6", "title": {"en": "Science with Purpose", "es": "Ciencia con Propósito"}, "text": {"en": "We apply scientific research to understand and address local environmental challenges, generating practical solutions.", "es": "Aplicamos la investigación científica para comprender y abordar los desafíos ambientales locales, generando soluciones prácticas."}, "imageUrl": "https://biophiliaweb.org/images/valores/science.png"},
        { "id": "value_4", "title": {"en": "Social Equity", "es": "Equidad Social"}, "text": {"en": "We work to ensure that all communities, especially the most vulnerable, have access to a healthy environment.", "es": "Trabajamos para que todas las comunidades, en especial las más vulnerables, tengan acceso a un medio ambiente sano."}, "imageUrl": "https://biophiliaweb.org/images/valores/social.png"},
        { "id": "value_5", "title": {"en": "Community Leadership", "es": "Liderazgo Comunitario"}, "text": {"en": "We empower local leaders and organizations to be protagonists in the conservation of their natural resources.", "es": "Empoderamos a líderes y organizaciones locales para que sean protagonistas en la conservación de sus recursos naturales."}, "imageUrl": "https://biophiliaweb.org/images/valores/liderazgo.png"},
        { "id": "value_1", "title": {"en": "Collaboration", "es": "Colaboración"}, "text": {"en": "We build alliances between communities, organizations, and governments to multiply the impact of our actions.", "es": "Construimos alianzas entre comunidades, organizaciones y gobiernos para multiplicar el impacto de nuestras acciones."}, "imageUrl": "https://biophiliaweb.org/images/valores/colaboracion.png"}
    ]
  },
  "ourNumbers": {
    "title": {"en": "Our Impact", "es": "Nuestro Impacto"},
    "stats": [
      { "id": "stat_1", "icon": "BookOpenIcon", "value": "+25", "label": {"en": "Conservation workshops and events", "es": "Talleres y jornadas de conservación"} },
      { "id": "stat_2", "icon": "UsersIcon", "value": "+300", "label": {"en": "Volunteers mobilized", "es": "Voluntarios movilizados"} },
      { "id": "stat_3", "icon": "LeafIcon", "value": "+1500", "label": {"en": "People made aware", "es": "Personas sensibilizadas"} }
    ],
    "galleryImages": [
      {"id": "gal_1", "url": "https://biophiliaweb.org/images/otros/5.jpg", "alt": "Volunteers working in a community garden"},
      {"id": "gal_2", "url": "https://biophiliaweb.org/images/otros/8.jpg", "alt": "Children learning about sea turtles"},
      {"id": "gal_3", "url": "https://biophiliaweb.org/images/otros/9.jpg", "alt": "Community members at a workshop"},
      {"id": "gal_4", "url": "https://biophiliaweb.org/images/otros/1.jpeg", "alt": "A group posing with their new plants"},
      {"id": "gal_5", "url": "https://biophiliaweb.org/images/otros/2.jpeg", "alt": "A young person planting a tree"},
      {"id": "gal_6", "url": "https://biophiliaweb.org/images/otros/3.jpeg", "alt": "Community discussion about conservation"}
    ]
  },
  "alliances": {
    "title": {"en": "Our Alliances", "es": "Nuestras Alianzas"},
    "description": {"en": "Collaboration is key to our success. We are proud to work with a diverse network of organizations, companies, and community groups to achieve our shared conservation goals.", "es": "La colaboración es clave para nuestro éxito. Estamos orgullosos de trabajar con una red diversa de organizaciones, empresas y grupos comunitarios para alcanzar nuestros objetivos comunes de conservación."},
    "partners": [
      { "id": "p_hf", "name": "Hispanic Federation", "logoUrl": "https://biophiliaweb.org/images/aliados/hispanic-federation-logo-color.png" },
      { "id": "p_ha", "name": "Hispanic Access Foundation", "logoUrl": "https://biophiliaweb.org/images/aliados/hispanic-access-logo.png" },
      { "id": "p_co", "name": "City of Orlando", "logoUrl": "https://biophiliaweb.org/images/aliados/city-of-orlando-logo.png" },
      { "id": "p_iw", "name": "Inwater Research Group", "logoUrl": "https://biophiliaweb.org/images/aliados/inwater-research-group-logo.png" },
      { "id": "p_oa", "name": "Orange Audubon Society", "logoUrl": "https://biophiliaweb.org/images/aliados/orange-audubon-society-logo.png" },
      { "id": "p_ec", "name": "The Episcopal Churches of Christ the King", "logoUrl": "https://biophiliaweb.org/images/aliados/episcopal-churches-logo.png" },
      { "id": "p_rf", "name": "Renacer Foundation", "logoUrl": "https://biophiliaweb.org/images/aliados/renacer-foundation-logo.png" },
      { "id": "p_cv", "name": "Casa Venezuela Orlando", "logoUrl": "https://biophiliaweb.org/images/aliados/casa-de-venezuela-orlando-logo.png" },
      { "id": "p_mf", "name": "Mi Familia en Acción", "logoUrl": "https://biophiliaweb.org/images/aliados/mi-familia-en-accion-logo.png" },
      { "id": "p_nc", "name": "Nuestra Cultura Outdoors", "logoUrl": "https://biophiliaweb.org/images/aliados/nuestra-cultura-outdoors-logo.png" }
    ]
  },
  "parallax2": {
    "title": {"en": "Our Planet, Our Future", "es": "Nuestro Planeta, Nuestro Futuro"},
    "text": {"en": "The time to act is now. Together, we can create a world where nature is respected, communities are strong, and future generations can enjoy a healthy and vibrant planet.", "es": "El momento de actuar es ahora. Juntos, podemos crear un mundo donde la naturaleza sea respetada, las comunidades sean fuertes y las futuras generaciones puedan disfrutar de un planeta sano y vibrante."},
    "imageUrl": "https://biophiliaweb.org/images/otros/Parallax_2.jpeg"
  }
}');

-- 3.2 About Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('aboutPage', '{
  "banner": {
    "title": {"en": "About Us", "es": "Nosotros"},
    "imageUrl": "https://biophiliaweb.org/images/banners/Banner_Nosotros.jpeg"
  },
  "history": {
    "title": {"en": "Our History", "es": "Nuestra Historia"},
    "text": {"en": "Founded on the principle of biophilia — the innate human tendency to connect with nature — our institute was born from the shared passion of a group of educators, scientists, and community leaders who saw an urgent need to bridge the growing gap between urban life and the natural world. Since our inception, we have been committed to creating meaningful experiences that not only educate but also inspire concrete actions for the conservation of our planet, starting in our own communities.", "es": "Fundado en el principio de la biofilia —la innata tendencia humana a conectar con la naturaleza—, nuestro instituto nació de la pasión compartida de un grupo de educadores, científicos y líderes comunitarios que vieron la necesidad urgente de cerrar la creciente brecha entre la vida urbana y el mundo natural. Desde nuestros inicios, nos hemos dedicado a crear experiencias significativas que no solo educan, sino que también inspiran acciones concretas para la conservación de nuestro planeta, comenzando en nuestras propias comunidades."},
    "imageUrl": "https://biophiliaweb.org/images/otros/Nosotros_Historia.jpeg"
  },
  "mission": {
    "title": {"en": "Our Mission", "es": "Nuestra Misión"},
    "text": {"en": "To inspire and empower communities to build a sustainable and resilient future through education, science with purpose, and a deep connection with nature.", "es": "Inspirar y empoderar a las comunidades para construir un futuro sostenible y resiliente, a través de la educación, la ciencia con propósito y la conexión profunda con la naturaleza."},
    "imageUrl": "https://biophiliaweb.org/images/otros/Nosotros_Mision.jpeg",
    "imageAlt": "A diverse group of volunteers planting trees in a park."
  },
  "vision": {
    "title": {"en": "Our Vision", "es": "Nuestra Visión"},
    "text": {"en": "We envision a world where humanity coexists in harmony with nature, where all communities have equitable access to a healthy environment, and where conservation is an intrinsic value in society.", "es": "Visualizamos un mundo donde la humanidad coexiste en armonía con la naturaleza, donde todas las comunidades tienen acceso equitativo a un ambiente sano y donde la conservación es un valor intrínseco en la sociedad."},
    "imageUrl": "https://biophiliaweb.org/images/otros/Nosotros_Vision.jpeg",
    "imageAlt": "A breathtaking landscape with mountains and a clear lake."
  },
  "work": {
    "title": {"en": "Our Work", "es": "Nuestro Trabajo"},
    "text": {"en": "Our work is structured around key thematic areas designed to maximize our impact. From restoring urban ecosystems and promoting sustainable agriculture to training environmental leaders and advocating for fair policies, each of our programs is a seed of change. We collaborate directly with communities to co-design projects that are culturally relevant and respond to their specific needs, ensuring that every action we take is both effective and lasting.", "es": "Nuestro trabajo se articula en áreas temáticas clave, diseñadas para maximizar nuestro impacto. Desde la restauración de ecosistemas urbanos y la promoción de la agricultura sostenible, hasta la formación de líderes ambientales y la abogacía por políticas justas, cada uno de nuestros programas es una semilla de cambio. Colaboramos directamente con las comunidades para co-diseñar proyectos que sean culturalmente relevantes y que respondan a sus necesidades específicas, asegurando que cada acción que emprendemos sea tan efectiva como duradera."},
    "imageUrl": "https://biophiliaweb.org/images/otros/Nosotros_Trabajo.jpeg",
    "imageAlt": "A researcher taking notes while examining a plant in a lush forest."
  }
}');

-- 3.3 Projects Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('projectsPage', '{
  "banner": {
    "title": {"en": "Our Programs", "es": "Nuestros Programas"},
    "imageUrl": "https://biophiliaweb.org/images/banners/Banner_Proyectos.jpeg"
  },
  "intro": {"en": "Our programs are the heart of our mission. Each one is designed to address critical environmental challenges through community action, education, and science. Explore our areas of work and discover how we are building a more sustainable future together.", "es": "Nuestros programas son el corazón de nuestra misión. Cada uno está diseñado para abordar desafíos ambientales críticos a través de la acción comunitaria, la educación y la ciencia. Explora nuestras áreas de trabajo y descubre cómo estamos construyendo juntos un futuro más sostenible."}
}');

-- 3.4 Project Detail Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('projectDetailPage', '{
  "backToProjects": {"en": "Back to All Programs", "es": "Volver a Todos los Programas"}
}');

-- 3.5 Team Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('teamPage', '{
  "banner": {
    "title": {"en": "Our Team", "es": "Nuestro Equipo"},
    "imageUrl": "https://biophiliaweb.org/images/banners/Banner_Equipo.jpeg"
  }
}');

-- 3.6 Blog Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('blogPage', '{
  "banner": {
    "title": {"en": "Blog", "es": "Blog"},
    "imageUrl": "https://biophiliaweb.org/images/banners/Banner_Blog.jpeg"
  },
  "featuredPostTitle": {"en": "Featured Post", "es": "Artículo Destacado"},
  "recentPostsTitle": {"en": "Recent Posts", "es": "Artículos Recientes"},
  "sharePostTitle": {"en": "Share this Post", "es": "Comparte este Artículo"}
}');

-- 3.7 Contact Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('contactPage', '{
  "banner": {
    "title": {"en": "Contact", "es": "Contacto"},
    "imageUrl": "https://biophiliaweb.org/images/banners/Banner_Contacto.jpeg"
  },
  "intro": {"en": "We would love to hear from you. Whether you have a question, a proposal, or simply want to learn more about our work, please do not hesitate to get in touch. We are here to connect.", "es": "Nos encantaría saber de ti. Si tienes una pregunta, una propuesta o simplemente quieres conocer más sobre nuestro trabajo, no dudes en ponerte en contacto. Estamos aquí para conectar."},
  "addressTitle": {"en": "Address", "es": "Dirección"},
  "phoneTitle": {"en": "Phone", "es": "Teléfono"},
  "emailTitle": {"en": "Email", "es": "Correo Electrónico"},
  "form": {
    "title": {"en": "Send us a Message", "es": "Envíanos un Mensaje"},
    "nameLabel": {"en": "Your Name", "es": "Tu Nombre"},
    "emailLabel": {"en": "Your Email", "es": "Tu Correo Electrónico"},
    "messageLabel": {"en": "Message", "es": "Mensaje"},
    "buttonText": {"en": "Send Message", "es": "Enviar Mensaje"}
  }
}');

-- 3.8 Donate Page
INSERT INTO `pages_content` (`page_name`, `content`) VALUES
('donatePage', '{
  "banner": {
    "title": {"en": "Donate", "es": "Donar"},
    "imageUrl": "https://biophiliaweb.org/images/banners/Banner_Donar.jpeg"
  },
  "intro": {"en": "Your generosity fuels our mission. Every donation allows us to continue our vital work in conservation, education, and community empowerment. Join us in building a more sustainable future.", "es": "Tu generosidad impulsa nuestra misión. Cada donación nos permite continuar nuestro vital trabajo en conservación, educación y empoderamiento comunitario. Únete a nosotros en la construcción de un futuro más sostenible."},
  "form": {
    "chooseAmount": {"en": "Choose an amount", "es": "Elige un monto"},
    "customAmount": {"en": "Or enter a custom amount", "es": "O ingresa un monto personalizado"},
    "firstName": {"en": "First Name", "es": "Nombre"},
    "lastName": {"en": "Last Name", "es": "Apellido"},
    "emailAddress": {"en": "Email Address", "es": "Correo Electrónico"},
    "paymentPlaceholder": {"en": "Secure payment processing will be handled here.", "es": "El procesamiento seguro de pagos se gestionará aquí."},
    "donateAmount": {"en": "Donate ${{amount}}", "es": "Donar ${{amount}}"}
  },
  "thankYou": {
    "title": {"en": "Thank You!", "es": "¡Gracias!"},
    "text": {"en": "Thank you for your generous donation of ${{amount}}. Your support makes our work possible and helps create a greener future for everyone.", "es": "Gracias por tu generosa donación de ${{amount}}. Tu apoyo hace posible nuestro trabajo y ayuda a crear un futuro más verde para todos."}
  }
}');

-- 4. PROJECTS
INSERT INTO `projects` (`id`, `title`, `description`, `imageUrl`, `imageAlt`, `detailImageUrl`, `display_order`) VALUES
('project_urban_forest', '{"en": "Urban Forest & Biodiversity", "es": "Bosque Urbano y Biodiversidad"}', '{"en": "Fostering greener cities by strengthening the urban canopy and biodiversity.", "es": "Fomentando ciudades más verdes mediante el fortalecimiento del dosel arbóreo y la biodiversidad urbana."}', 'https://biophiliaweb.org/images/proyectos/P1.jpeg', 'Community members planting trees.', 'https://biophiliaweb.org/images/proyectos/P1-Banner.jpeg', 1),
('project_urban_harvest', '{"en": "Sustainable Urban Agriculture", "es": "Agricultura Urbana Sostenible"}', '{"en": "Developing community gardens to improve food security and environmental education.", "es": "Desarrollando huertos comunitarios para mejorar la seguridad alimentaria y la educación ambiental."}', 'https://biophiliaweb.org/images/proyectos/P2.jpeg', 'Volunteers working in a community garden.', 'https://biophiliaweb.org/images/proyectos/P2-Banner.jpeg', 2),
('project_ocean_guardians', '{"en": "Ocean Guardians", "es": "Guardianes del Océano"}', '{"en": "Educational workshops and coastal cleanups to protect our marine ecosystems.", "es": "Talleres educativos y jornadas de limpieza costera para proteger nuestros ecosistemas marinos."}', 'https://biophiliaweb.org/images/proyectos/P3.jpeg', 'Children learning about sea turtles.', 'https://biophiliaweb.org/images/proyectos/P3-Banner.jpeg', 3),
('project_symbiosis', '{"en": "Symbiosis", "es": "Simbiosis"}', '{"en": "Connecting communities with their natural environment through hiking and environmental action.", "es": "Conectando a las comunidades con su entorno natural a través del senderismo y la acción ambiental."}', 'https://biophiliaweb.org/images/proyectos/P4.jpeg', 'A group of people hiking in a forest.', 'https://biophiliaweb.org/images/proyectos/P4-Banner.jpeg', 4),
('project_eco_resilience', '{"en": "Urban Eco-Resilience", "es": "Eco-Resiliencia Urbana"}', '{"en": "Preparing communities for extreme weather events like hurricanes and heat waves.", "es": "Preparando a las comunidades para enfrentar eventos climáticos extremos como huracanes y olas de calor."}', 'https://biophiliaweb.org/images/proyectos/P5.jpeg', 'A graphic showing a hurricane plan.', 'https://biophiliaweb.org/images/proyectos/P5-Banner.jpeg', 5),
('project_ecopro_youth', '{"en": "EcoPro Youth", "es": "Jóvenes EcoPro"}', '{"en": "Training young people as environmental leaders to address urban heat island effects.", "es": "Formando a jóvenes como líderes ambientales para enfrentar los efectos de las islas de calor urbano."}', 'https://biophiliaweb.org/images/proyectos/P6.jpeg', 'Young people using thermometers to measure heat.', 'https://biophiliaweb.org/images/proyectos/P6-Banner.jpeg', 6),
('project_hispanic_observatory', '{"en": "Hispanic Environmental Observatory", "es": "Observatorio Ambiental Hispano"}', '{"en": "A space for connection, recognition, and strengthening of environmental initiatives in the Hispanic community.", "es": "Un espacio de encuentro, reconocimiento y fortalecimiento de las iniciativas ambientales de la comunidad hispana."}', 'https://biophiliaweb.org/images/proyectos/P7.jpeg', 'A group of people networking at an event.', 'https://biophiliaweb.org/images/proyectos/P7-Banner.jpeg', 7);

-- 5. PROJECT ACTIVITIES (Note: Some descriptions are duplicated as per the source text)
-- Activities for Urban Forest & Biodiversity
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_urban_forest_1', 'project_urban_forest', '2024-08-18', '{"en": "First tree of the Community Faith Forest project in Orlando, FL.", "es": "Primer árbol del proyecto Bosque Comunitario de la Fe, en Orlando. FL."}', '{"en": "On August 18, in the Azalea Park community of Orlando, Florida, we launched the project: ''Community Faith Forest, an ecological corridor in Central Florida.'' Neighbors and the leading organizations gathered at a resident''s home to plant the first tree, marking the beginning of our efforts to strengthen the urban forest in this community. Commissioner Tony Ortiz of Orlando''s District 2 participated, reaffirming our collective commitment. This project is executed by Christ the King Episcopal Church in Orlando, FL, in partnership with Renacer Foundation, the Hispanic Environmental Observatory, Calao Corp, and Corpus Care, funded by the #NuestrosBosques program of the Hispanic Access Foundation.", "es": "El 18 de agosto, en la comunidad de Azalea Park, en Orlando, Florida, iniciamos el proyecto: “Bosque Comunitario de Fe, un corredor ecológico en la Florida Central”, donde vecinos y las organizaciones que lideran el proyecto, nos reunimos en casa de una residente de la comunidad para plantar el primer árbol, lo que marca el inicio de nuestros esfuerzos para fortalecer el arbolado y el bosque urbano de esta comunidad. La actividad, contó con la participación del Comisionado Tony Ortiz, del Distrito 2 de la Ciudad de Orlando, quien junto a las organizaciones y vecinos reafirmamos nuestro compromiso con la conservación de los árboles y bosques de la zona, destacando su importancia para el bienestar y la mejora de la calidad de vida de toda la comunidad. El proyecto, ''Bosque Comunitario de Fe, un corredor ecológico en la Florida Central'', está ejecutado por Christ the King Episcopal Church in Orlando, FL, en alianza con Renacer Foundation, el Observatorio Ambiental Hispano, Calao Corp y Corpus Care, mediante el financiamiento del programa #NuestrosBosques de la Hispanic Access Foundation."}', 'https://biophiliaweb.org/images/actividades/1.jpeg', 1),
('activity_urban_forest_2', 'project_urban_forest', '2025-06-12', '{"en": "Practical workshop: ''Importance of trees in urban ecosystems''.", "es": "Taller práctico: “Importancia de los árboles en los ecosistemas urbanos”."}', '{"en": "On June 12, 2025, we held a practical workshop on the ''Importance of trees in urban ecosystems'' for 32 youths from the 2025 Summer Youth Program in Orlando, led by Christ the King Episcopal Church. Participants learned about the ecological function of trees in urban settings and practiced tree propagation using the air layering technique, a method that allows for reproducing species without seeds.", "es": "El 12 de Junio de 2025, realizamos el taller práctico: “Importancia de los árboles en los ecosistemas urbanos”, dirigido a 32 jóvenes del Summer Youth Program 2025 en la ciudad de Orlando, liderado por  Christ the King Episcopal Church in Orlando . Durante la jornada, los participantes aprendieron sobre la función ecológica de los árboles en entornos urbanos, y aprendieron sobre la propagación de árboles mediante la técnica del acodo aéreo, un método de propagación vegetativa que permite reproducir especies sin semilla, mediante una incisión en la rama, aplicación de enraizante y sustrato húmedo, favoreciendo así, el desarrollo de las raíces desde las propias ramas. Esta experiencia, integró conocimiento científico y la acción comunitaria para la conservación del bosque urbano."}', 'https://biophiliaweb.org/images/actividades/9.jpg', 2),
('activity_urban_forest_3', 'project_urban_forest', '2025-06-28', '{"en": "Invasive plant removal day at Apopka Birding Park forest.", "es": "Jornada de remoción de plantas invasoras en el bosque del Apopka Birding Park."}', '{"en": "On June 28, 2025, at least 30 Hispanics joined to support the Orange Audubon Society in a day of invasive plant removal in the forest of the Lake Apopka wildlife drive, part of the ''Apopka Birding Park'' nature center and habitat restoration project. Volunteers from Christ the King Episcopal Church, Nuestra Cultura Outdoors, Renacer Foundation, the Hispanic Environmental Observatory, and Vente Venezuela removed harmful plants, collected debris, built birdhouses, and reflected on the importance of forests.", "es": "El 28 de junio de 2025, al menos 30 hispanos nos unimos para apoyar a Orange Audubon Society, en una jornada de remoción de plantas invasoras en el bosque de la ruta de vida silvestre en el Lago de Apopka, area que forma parte del proyecto del centro natural y restauración de hábitats: ''Apopka Birding Park''. Durante la actividad, voluntarios de las organizaciones Christ the King Episcopal Church in Orlando, FL Nuestra Cultura Outdoors, Renacer Foundation, el Observatorio Ambiental Hispano y Vente Venezuela, desarrollamos remoción de plantas nocivas para este ecosistema, recogimos escombros, realizamos casas para aves, y además, reflexionamos sobre la importancia de los bosques como soporte para estos ecosistemas e influencia en el aumento de nuestra calidad de vida."}', 'https://biophiliaweb.org/images/actividades/10.jpg', 3),
('activity_urban_forest_4', 'project_urban_forest', '2025-04-26', '{"en": "Workshop: ''My Friend the Tree'', as part of the Paths to Science program.", "es": "Taller: “Mi amigo el árbol”,  en el marco del programa Senderos a la ciencia."}', '{"en": "On April 26, 2025, we held the workshop ''My Friend the Tree'' as part of the ''Paths to Science'' program, developed by Hispanic Access Foundation and Renacer Foundation. The activity was part of the ''Tree Festival'', a beautiful eco-citizen gathering that united organizations and neighbors to celebrate #arborday. Participants learned about the role of trees, drew their favorite tree, developed seedlings, took home plants they transplanted themselves, planted fruit trees, and learned about careers in environmental sciences.", "es": "El 26 de abril de 2025, desarrollamos el taller: “Mi amigo el árbol”,  en el marco del programa ''Senderos a la ciencia'', el cual es desarrollado por Hispanic Access Foundation y Renacer Foundation. La actividad se enmarcó en el ''Festival del árbol'', un hermoso encuentro Eco-Ciudadano que unió a organizaciones y vecinos para celebrar el #arborday. Los participantes aprendieron sobre el rol e importancia de los árboles y el bosque urbano, dibujaron su árbol favorito, desarrollaron semilleros, llevaron plantas a sus hogares que ellos mismos trasplantaron, sembramos árboles frutales, hicieron lectura de temperaturas para evidenciar el rol de los árboles en su comunidad, conocieron como vincularse a carreras de ciencias ambientales, y a las organizaciones que ofrecen apoyo en estas carreras. A su vez, organizaciones participantes entregaron plantas y realizaron rifas con regalos vinculados a la conservación de los árboles."}', 'https://biophiliaweb.org/images/actividades/22.jpeg', 4),
('activity_urban_forest_5', 'project_urban_forest', '2025-04-10', '{"en": "Workshop: ''Heat Islands and Urban Forests in Orlando''.", "es": "Taller: “Islas de calor y bosques urbano en Orlando”."}', '{"en": "On April 10, 2025, in Orlando, we conducted the workshop ''Heat Islands and Urban Forests'' for 25 youths from Little Steps Academy, as part of the ''Innovation programming for youth'' project. Participants took temperature readings in different community areas to analyze the causes and effects of heat islands and to understand the importance of the urban forest in mitigating them. The activity was part of our #EarthMonth celebration and was developed in partnership with Renacer Foundation, Christ the King Episcopal Church, and Little Steps Academy.", "es": "El 10 de abril de 2025, en la ciudad de Orlando, Florida, realizamos el taller: “Islas de calor y bosques urbano”. Dirigido a 25 jóvenes del Little Steps Academy, en el marco del proyecto ''Innovation programming for youth'', que desarrolla la Christ the King Episcopal Church in Orlando, FL y Orange County.  Durante el taller, los participantes realizaron toma de lectura de temperatura en diferentes zonas referenciales de la comunidad, para analizar y dialogar sobre causas, consecuencias y efectos de las islas de calor en los ciudadanos y ecosistemas. Y a su vez, conocer la importancia del bosque urbano y el rol de los árboles como factor elemental en la mitigación de las islas de calor. La actividad, forma parte de nuestra celebración del #EarthMonth y fue desarrollada en alianza entre Renacer Foundation, Christ the King Episcopal Church, la Little Steps Academy, y el Observatorio Ambiental Hispano. Agradecemos a la Directora Rut Ayala por el apoyo, a los profesores y a jóvenes participantes."}', 'https://biophiliaweb.org/images/actividades/27.jpeg', 5);
-- Activities for Sustainable Urban Agriculture
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_urban_harvest_1', 'project_urban_harvest', '2024-08-26', '{"en": "Papayas, seedlings, and mental health at the Engelwood garden in Orlando.", "es": "Papayas, semilleros y salud mental en el huerto de Engelwood, en Orlando."}', '{"en": "On August 26, we held a ''Garden and Coffee'' learning day at the Engelwood Neighborhood Center community garden. Seniors from the center and Magnolias residence learned about food production through agricultural and hydroponic techniques, harvested papayas, and helped prepare lettuce seedlings. They also shared breakfast and received a mental health talk from the Renacer Foundation team. This activity is part of the ''Community Faith Forest'' project.", "es": "El 26 de agosto, desarrollamos la jornada de aprendizaje “Huerto y café”, en el huerto comunitario del Engelwood Neighborhood Center en Orlando, la actividad contó con la participación de adultos mayores del mencionado centro y de la residencia Magnolias, quienes aprendieron sobre la producción de alimentos mediante técnicas agrícolas e hidropónicas, cosecharon papayas, y ayudaron a desarrollar semilleros de lechugas. Además, compartieron un desayuno y recibieron una charla de salud mental del equipo de Renacer Foundation. La actividad, forma parte de las acciones previstas en el proyecto, ''Bosque Comunitario de Fe, un corredor ecológico en la Florida Central'', ejecutado por Christ the King Episcopal Church in Orlando, FL, en alianza con Renacer Foundation, el Observatorio Ambiental Hispano, Calao Corp y Corpus Care, mediante el financiamiento del programa #NuestrosBosques de la Hispanic Access Foundation."}', 'https://biophiliaweb.org/images/actividades/2.jpeg', 1),
('activity_urban_harvest_2', 'project_urban_harvest', '2024-07-17', '{"en": "Practical workshop: ''Community garden: agriculture in our backyard''.", "es": "Taller practico: ''Huerto comunitario: la agricultura en nuestro patio''."}', '{"en": "On July 17, 2024, we held the workshop ''Community garden: agriculture in our backyard'' for 22 young people in Orlando, part of the summer youth program by the Episcopal Churches of Christ the King and CareerSource Central Florida. The youth learned about urban agriculture while performing maintenance, harvesting, transplanting crops, and preparing seedlings, understanding the benefits of growing our own food.", "es": "El 17 de julio DE 2024, desarrollamos el taller practico: ''Huerto comunitario: la agricultura en nuestro patio''. Dirigido a 22 jóvenes de Orlando, Florida, participantes del programa juvenil de verano desarrollado por en la Episcopal Churches of Christ the King Episcopal Church in Orlando, FL  , y CareerSource Central Florida. Durante la actividad, los jóvenes aprendieron conceptos sobre agricultura urbana, mientras realizaban actividades de mantenimiento, cosecha, transplante de cultivos y semilleros. Y a su vez, conocieron los diferentes beneficios que tiene la producción de nuestros propios alimentos en casa."}', 'https://biophiliaweb.org/images/actividades/15.jpg', 2),
('activity_urban_harvest_3', 'project_urban_harvest', '2025-05-23', '{"en": "Volunteer day at the Engelwood Neighborhood Center community garden.", "es": "Jornada de voluntariado en el huerto comunitario del Engelwood Neighborhood Center."}', '{"en": "On May 23, 2025, we held a maintenance and harvesting day at the Engelwood Neighborhood Center community garden with the support of Renacer Foundation volunteers and local community leaders. Volunteers learned about urban agriculture while cleaning garden beds, pruning tomato plants, harvesting, and more. Join our free, ongoing workshops on sustainable urban agriculture and hydroponics.", "es": "El 23 de mayo de 2025, desarrollamos una jornada de mantenimiento y cosecha en el huerto comunitario del Engelwood Neighborhood Center in Orlando, con el apoyo del voluntariado de Renacer Foundation y líderes comunitarios de la zona. Durante la actividad, los voluntarios conocieron sobre agricultura urbana, huertos comunitarios y la producción de alimentos, mientras realizaron tareas de limpieza de canteros, poda plantas de tomate, aparcamiento de los cultivos, cosecha, entre otros. Únete a nuestras jornadas voluntarias, dónde aprenderás todo sobre agricultura urbana sostenible y hidroponía en los talleres que desarrollamos en el huerto comunitario de manera gratuita y permanente."}', 'https://biophiliaweb.org/images/actividades/16.jpg', 3),
('activity_urban_harvest_4', 'project_urban_harvest', '2025-05-14', '{"en": "Session: ''Learning to plant in the community garden''.", "es": "Jornada: “Aprendiendo a sembrar en el huerto comunitario”"}', '{"en": "On May 14, 2025, we held the session ''Learning to plant in the community garden'' for 21 children from the Engelwood Neighborhood Center in Orlando. We connected and taught the children to work with the earth, observe plant growth, how they relate to each other, how to harvest, and collaborate as a community, fostering values of sustainability, healthy eating, ecology, and cooperation.", "es": "El 14 de mayo de 2025, desarrollamos la jornada “Aprendiendo a sembrar en el huerto comunitario”, una actividad dirigida a 21 niños del Engelwood Neighborhood Center de la ciudad de Orlando, conectamos y enseñamos a los niños a trabajar con la tierra, observar el crecimiento de las plantas, como se vinculan entre si, como cosechar, y colaborar en comunidad. Estimulando valores de sostenibilidad, alimentación saludable, ecología y cooperativismo. ''Sin conexión, no hay transformación: Al experimentar nuestra conexión con otros seres vivos y entornos naturales dentro del contexto urbano, afianzamos el entendimiento de que somos naturaleza y co-habitamos en un mismo ecosistema''."}', 'https://biophiliaweb.org/images/actividades/19.jpeg', 4),
('activity_urban_harvest_5', 'project_urban_harvest', '2025-04-30', '{"en": "Informative session: ''The garden, growing healthy food''.", "es": "Jornada informativa: “El huerto, cultivando alimentos sanos”."}', '{"en": "On April 30, 2025, we began our partnership with the Engelwood Neighborhood Center with an informative session ''The garden, growing healthy food'' for seniors at the community center. Participants learned about the concepts and importance of sustainable urban agriculture while weeding garden beds and harvesting vegetables. This partnership includes a training program in sustainable urban agriculture with weekly workshops for citizens of all ages and a monthly practical workshop and forum for community leaders.", "es": "El 30 de abril de 2025, iniciamos la alianza con el Engelwood Neighborhood Center de la Ciudad de Orlando, con una jornada informativa “El huerto, cultivando alimentos sanos”, dirigido a adultos mayores que hacen vida este centro comunitario. En esta ocasión, los participantes aprendieron sobre conceptos e importancia de la agricultura urbana sostenible y la producción de nuestros propios alimentos, a la vez, que quitamos hierbas en los canteros, y cosechamos algunos vegetales. La alianza contempla, un programa de formación en agricultura urbana sostenible en el jardín comunitario. El programa, promoverá talleres prácticos semanalmente, dirigidos a ciudadanos de todas las edades que participan en las diferentes actividades de este centro. Y además, desarrollaremos un taller práctico y un foro mensual dirigido a líderes y vecinos de las diferentes comunidades de Orlando. Todos los talleres lo hacemos usando el método de ''aprender-haciendo''."}', 'https://biophiliaweb.org/images/actividades/21.jpeg', 5),
('activity_urban_harvest_6', 'project_urban_harvest', '2025-02-26', '{"en": "Practical workshop on planting vegetables by transplant. Orlando.", "es": "Taller práctico sobre siembra de hortalizas por trasplante. Orlando."}', '{"en": "On February 26, 2025, at the Engelwood Neighborhood Center community garden, we continued our urban agriculture training activities for young beneficiaries of the ''Innovation programming for youth''. We held a ''Practical workshop on planting vegetables by transplant''. Participants went through the entire process of preparing beds, substrate, checking the irrigation system, selecting and combining plants, and planting. This way, they could ''learn-by-doing'' while we discussed concepts and the importance of urban agriculture.", "es": "El 26 de febrero de 2025, en el jardín comunitario del Engelwood Neighborhood Center de la ciudad de Orlando, continuamos con las actividades de formación en agricultura urbana a jóvenes beneficiarios del ''Innovation programming for youth'', que desarrolla la Christ the King Episcopal Church en alianza con Orange County. En esta ocasión, desarrollamos el ''Taller práctico sobre siembra de hortalizas por trasplante''. Mediante el taller, los participantes desarrollaron todo el proceso de preparación de canteros, sustrato, revisión del sistema de riego, selección y combinación de plantas y la siembra. De esta manera, pudieron ''aprender-haciendo'', mientras dialogamos sobre conceptos e importancia de la agricultura urbana y la producción de nuestros patios alimentos."}', 'https://biophiliaweb.org/images/actividades/31.jpeg', 6);
-- Activities for Ocean Guardians
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_ocean_guardians_1', 'project_ocean_guardians', '2024-08-05', '{"en": "''Friends of the Turtles'' workshop teaches youth to protect our oceans.", "es": "Taller de tortugas marinas enseña a jóvenes a proteger nuestros océanos."}', '{"en": "On August 5, we held the ''Friends of the Turtles'' workshop for 32 young people from Orlando, participants of the Summer Youth Program run by Christ the King Episcopal Church and CareerSource Central Florida. In a fun and practical way, they learned about the importance of sea turtles, their characteristics, types, habits, reproduction, and how we can contribute to their conservation. They also received an ocean conservation kit. The workshop was possible thanks to the partnership between Biophilia Institute, the Hispanic Environmental Observatory, and Inwater Research Group.", "es": "El pasado 5 de agosto, desarrollamos el taller: ''Amigos de las tortugas'', dirigido a 32 jóvenes de la ciudad de Orlando, participantes del Summer Youth Program ejecutado por la Christ the King Episcopal Church, junto a CareerSource Central Florida. Durante la actividad, los jóvenes aprendieron, de manera divertida y práctica, sobre la importancia de las tortugas marinas, características, tipos, hábitos, reproducción y cómo podemos contribuir a su conservación. También recibieron un kit de conservación de océanos. El taller fue posible, gracias a la alianza entre Biophilia Institute, el Observatorio Ambiental Hispano y Inwater Research Group, para seguir formando guardianes del océano en Florida Central."}', 'https://biophiliaweb.org/images/actividades/3.jpeg', 1),
('activity_ocean_guardians_2', 'project_ocean_guardians', '2025-07-05', '{"en": "''Friends of the Turtles'' workshop for the AMOR AL PRÓJIMO Association in Apopka, Florida.", "es": "Taller: “Amigos de las tortugas”, dirigido a la Asociación AMOR AL PRÓJIMO, en Apopka, Florida."}', '{"en": "On July 5, 2025, we conducted the ''Friends of the Turtles'' workshop for families of the AMOR AL PRÓJIMO Association in rural Apopka, Florida. The event was attended by 28 Hispanics, including children, youth, and adults, who learned in a fun and practical way about the importance of sea turtles and their conservation. This activity was in support of the ''Por Nosotros'' program, facilitated by Fundación Crecemos Todos in coordination with Hispanic Federation and Advent Health. The workshop is developed thanks to our partnership with Inwater Research Group, supported by the Sea Turtle License Plate Grant.", "es": "El 5 de julio de 2025, desarrollamos el taller: “Amigos de las tortugas”, dirigido a familias de la Asociación AMOR AL PRÓJIMO, ubicada en la zona rural de Apopka, Florida. La jornada, contó con la participación de 28 hispanos entre niños, jóvenes y adultos, quienes aprendieron de manera divertida y práctica, sobre la importancia de las tortugas marinas, características, tipos, hábitos, reproducción y como podemos contribuir a su conservación. Esta actividad se realizó en apoyo al programa “Por Nosotros”, que actualmente facilita la Fundación Crecemos Todos en coordinación con Hispanic Federation y Advent Health. El taller: ''Amigos de las tortugas'', lo desarrollamos gracias a nuestra alianza con Inwater Research Group quien recibido apoyo de Sea Turtle License Plate Grant, para seguir formando guardianes del océano en Florida Central."}', 'https://biophiliaweb.org/images/actividades/8.jpg', 2),
('activity_ocean_guardians_3', 'project_ocean_guardians', '2025-06-16', '{"en": "''Friends of the Turtles'' workshop with youth from Orlando, Florida.", "es": "Taller: ''Amigos de las Tortugas con jóvenes de Orlando, Florida''."}', '{"en": "On June 16, 2025, for #WorldSeaTurtleDay, we held the ''Friends of the Turtles'' workshop with 32 youths from the CareerSource Central Florida Summer Youth Program. They learned about the world of sea turtles: their habits, habitats, and how to protect them. They also took home a conservation kit to share with their families! Thanks to the support of Inwater Research Group and the Sea Turtle License Plate Grant, we continue to train ocean guardians in Central Florida.", "es": "El 16 de junio de 2025, en el marco del #Día Mundial De Las Tortugas Marinas, realizamos el taller ''Amigos de las Tortugas'' con 32 Jóvenes del Summer Youth Program de CareerSource Central Florida aprendieron, de forma divertida y práctica, sobre el mundo de las tortugas marinas: sus hábitos, hábitats y cómo protegerlas. Además, ¡se llevaron a casa un kit de conservación para compartir en familia! Gracias al apoyo de Inwater Research Group @inwaterresearch y el Sea Turtle License Plate Grant, seguimos formando guardianes del océano en Florida Central."}', 'https://biophiliaweb.org/images/actividades/11.jpg', 3),
('activity_ocean_guardians_4', 'project_ocean_guardians', '2025-04-16', '{"en": "''Friends of the Turtles'' workshop at the Engelwood Neighborhood Center, Orlando.", "es": "Taller: “Amigos de las tortugas. en el Engelwood Neighborhood Center. Orlando”."}', '{"en": "On April 16, 2025, at the Engelwood Neighborhood Center in Orlando, at least 15 children participated in our fourth ''Friends of the Turtles'' workshop. Participants learned practically about the importance, characteristics, types, habits, reproduction, and conservation of sea turtles. The event was also an opportunity for Ivette Fernández, coordinator of this educational project led by Inwater Research Group in Florida, to formalize our partnership by delivering the educational kit with all the materials to conduct this workshop in Central Florida. Contact us if you want to bring this free workshop to your educational institution or community.", "es": "El 16 de abril de 2025, en el Engelwood Neighborhood Center de la ciudad de Orlando, al menos 15 niños participaron en nuestro cuarto taller “Amigos de las tortugas”. Durante el taller, los participantes aprendieron de manera práctica sobre la importancia, características, tipos, hábitos, reproducción y como contribuir en la conservación de las tortugas marinas. La actividad fue propicia para que Ivette Fernández, coordinadora de este proyecto educativo dirigido por Inwater Research Group en Florida, formalizara nuestra alianza, haciendo entrega del kit (maleta) educativo con todos los materiales para desarrollar este taller en la Florida Central. Si deseas llevar este taller a tu institución educativa o comunidad contáctanos, es gratuito."}', 'https://biophiliaweb.org/images/actividades/26.jpeg', 4);
-- Activities for Symbiosis
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_symbiosis_1', 'project_symbiosis', '2024-08-01', '{"en": "From branch to forest: science and community in Azalea Park, Orlando, FL.", "es": "De la rama al bosque: ciencia y comunidad en Azalea Park, Orlando. FL."}', '{"en": "On August 1, we held a practical workshop on ''Tree Propagation Techniques in Urban Ecosystems'' for 30 young people in Azalea Park, Orlando. Participants learned to propagate trees using air layering, practicing incisions, applying rooting hormone, and using recycled plastic to maintain moisture. They also observed root formation from a previous workshop in June, cut the rooted branches, and transplanted them into pots. The experience combined science and community action for urban forest conservation, as part of the ''Community Faith Forest'' project.", "es": "El pasado 1 de agosto, realizamos el taller práctico: ''Técnicas de propagación de árboles en ecosistemas urbanos'', dirigido a 30 jóvenes del Parque Azalea de Orlando. Durante la jornada, los participantes aprendieron sobre la propagación de árboles mediante la técnica de acodo aéreo, practicaron la realización de incisiones en ramas seleccionadas, la aplicación de hormona de enraizamiento y el uso de plástico reciclado para mantener el sustrato húmedo en el punto de incisión. Las áreas tratadas se envolvieron en plástico negro para simular condiciones óptimas de enraizamiento. También observaron la formación de raíces en las ramas (resultado del primer taller en junio, con jóvenes de la misma zona). Cortaron la rama y la trasplantaron a macetas. La experiencia fue una combinación de ciencia y acción comunitaria para la conservación de los bosques urbanos. Estas actividades se desarrollan dentro del proyecto ''Bosque Comunitario de la Fe, un corredor ecológico urbano en Florida Central''."}', 'https://biophiliaweb.org/images/actividades/4.jpeg', 1),
('activity_symbiosis_2', 'project_symbiosis', '2025-06-07', '{"en": "Event: ''Exploring Wekiwa Springs State Park, Apopka, Florida''.", "es": "Jornada: ''Explorando el Wekiwa Springs State Park, Apopka. Florida''."}', '{"en": "On June 7, 2025, celebrating World Environment Day and Hiking Day, we held the ''Exploring Wekiwa Springs State Park'' event. At least 30 Hispanic participants of different ages entered the forest, connected, learned, and helped conserve the ecosystem by collecting solid waste. It was an extraordinary community environmental action activity, organized by Nuestra Cultura Outdoors, Renacer Foundation, Casa Venezuela Orlando, and the Hispanic Environmental Observatory.", "es": "El 7 de junio de 2025, a propósito de las celebraciones del Día Mundial del Ambiente y Día del Senderismo, desarrollamos la jornada ''Explorando el Wekiwa Springs State Park'', donde al menos 30 participantes hispanos de diferentes edades, nos adentramos en el bosque y pudimos conectarnos, aprender y ayudar en la conservación de este ecosistema mediante la recolección de residuos sólidos. Fue una extraordinaria actividad de acción ambiental comunitaria, organizada por Nuestra Cultura Outdoors, Renacer Foundation, Casa Venezuela Orlando y el Observatorio Ambiental Hispano. Una experiencia llena de salud, ecología y entretenimiento, que permitió a los participantes disfrutar del río y los recursos naturales que ofrece el Parque Estadal Wekiwa Springs."}', 'https://biophiliaweb.org/images/actividades/14.jpg', 2),
('activity_symbiosis_3', 'project_symbiosis', '2025-04-16', '{"en": "Youth environmental day at the University of Central Florida.", "es": "Jornada ambiental juvenil en la Universidad Central de Florida."}', '{"en": "On April 16, 2025, as part of the #EarthMonth celebrations, we were invited by the Hispanic Federation to an environmental youth day at the University of Central Florida. The objective was to raise awareness about the importance of voting and how it can influence the promotion of public environmental policies that guarantee sustainability on our planet!", "es": "El 16 de abril de 2025, en el marco de las celebraciones del #EarthMonth , fuimos invitados por Hispanic Federation para acompañarlos en una jornada ambiental juvenil en la Universidad Central de Florida, con el objetivo de sensibilizar sobre la importancia del voto, y como el mismo, puede incidir en tener representantes que promuevan políticas públicas ambientales que nos garantice la sustentabilidad en el planeta!"}', 'https://biophiliaweb.org/images/actividades/25.jpeg', 3),
('activity_symbiosis_4', 'project_symbiosis', '2025-03-08', '{"en": "Tour: ''Bird watching at Orlando Wetlands''.", "es": "Paseo: Buscando pájaros en el Orlando Wetlands."}', '{"en": "On March 8, 2025, 20 Hispanics, including children, youth, and adults, attended the ''Bird watching at Orlando Wetlands'' event. Participants enjoyed a tour with excellent guidance in Spanish from Gilberto Sánchez, an active volunteer at #OrlandoWetlands specialized in bird watching. They observed and learned about the species, their ecological role, conservation needs, and the importance of the wetland. This is the fourth consecutive year Orange Audubon has promoted this activity for the Spanish-speaking community and the third year the Hispanic Environmental Observatory has joined.", "es": "El 8 de marzo de 2025, 20 hispanos entre niños, jóvenes y adultos se hicieron presentes en el evento ''Buscando pájaros en el Orlando Wetlands'', durante el mismo, los participantes disfrutaron de un recorrido con excelente guiatura en español a través de Gilberto Sánchez, un voluntario activo del #OrlandoWetlands y especializado en observación de aves, además de toda la información ambiental e historia de este humedal. Igualmente, pudieron observar y aprender sobre las especies, su rol ecológico, las necesidades de conservación y la importancia que tiene dicho humedal. Además, la actividad permitió consolidar alianzas para llevar ciencias ambientales a la comunidad hispana, rompiendo barreras del idioma y estimulando la participación de los mismos en la conservación de los ecosistemas. Este es el cuarto año consecutivo que Orange Audubon promueve esta actividad dirigida a la comunidad hispanohablante y tercer año que el Observatorio Ambiental Hispano se une para el desarrollo de la misma."}', 'https://biophiliaweb.org/images/actividades/30.jpeg', 4);
-- Activities for Urban Eco-Resilience
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_eco_resilience_1', 'project_eco_resilience', '2025-07-31', '{"en": "Citizen campaign in Spanish for extreme heat.", "es": "Campaña ciudadana en español por calor extremo."}', '{"en": "On July 31, 2025, we launched a social media campaign to alert citizens about the health impacts of extreme heat. In recent days in Central Florida, we have experienced oppressive heat, with high temperatures exceeding averages in recent years. We share this information with you to be prepared and take timely measures against heat-related health symptoms.", "es": "El 31 de julio 2025, realizamos una campaña en redes sociales para alertar a la ciudadanía sobre las incidencias en la salud del calor extremo. Los últimos días en la Florida Central, hemos experimentado calores agobiantes, con altas temperaturas que superan los promedios en los últimos años. Compartimos con ustedes, está información para que estén prevenidos y puedan tomar medidas oportunas ante sintonías que relacionadas al calor y su salud."}', 'https://biophiliaweb.org/images/actividades/5.jpg', 1),
('activity_eco_resilience_2', 'project_eco_resilience', '2025-06-10', '{"en": "Informative sessions: ''From Calm: How to build your hurricane plan''.", "es": "Jornadas informativas: ''Desde la calma: Cómo armar tu plan de huracanes ''."}', '{"en": "Between June 10 and 14, 2025, marking the start of hurricane season, we organized with the Hispanic Federation the informative sessions: ''From Calm: How to build your hurricane plan''. These were virtual coffee talks with specialists from NOAA, the City of Orlando, and the American Red Cross. The goal was to provide information and connect the Hispanic community with authorities and leading organizations on the topic. The sessions were moderated by Laudi Campo, Director of Hispanic Federation Florida, and Faruk Bagdah, CEO of Biophilia Institute.", "es": "Entre el 10 y 14 de junio de 2025, con motivo del inicio de la temporada de huracanes, oranizamos junto a Hispanic Federation, las jornadas informativas: ''Desde la calma: Cómo armar tu plan de huracanes '', cafecitos virtuales con especialistas de la NOAA, La Ciudad de Orlando y la Cruz Roja de los EEUU. El objetivo es facilitar espacios de información y conexión entre la comunidad hispana, autoridades y organizaciones líderes en el tema. Los encuentros fueron moderados por Laudi Campo, Directora de Hispanic Federation Florida, y Faruk Bagdah, CEO de Biophilia Institute. Durante las jornadas, participaron especialista en la materia como Manuel Soto, Gerente de Emergencias de la Ciudad de Orlando, quien habló sobre los pasos claves para crear un plan familiar, errores comunes que debes evitar y los recursos disponibles en Florida. Compartiendo información clara y útil para que tú y tu familia estén preparados esta temporada. Además, Armando Falcón, Gerente de Participación Comunitaria y Alianzas de la Cruz Roja de EEUU, quien conversó sobre el rol de la Cruz Roja y sus estrategias de abordaje a poblaciones hispanas vulnerables, recursos disponibles con los que cuentan para la comunidad y recomendaciones claras para armar tu plan familiar ante emergencias."}', 'https://biophiliaweb.org/images/actividades/13.jpg', 2),
('activity_eco_resilience_3', 'project_eco_resilience', '2025-04-30', '{"en": "Informative sessions: ''From Calm: How to build your hurricane plan''. (Hydroponics Workshop)", "es": "Jornadas informativas: ''Desde la calma: Cómo armar tu plan de huracanes ''. (Taller de Hidroponía)"}', '{"en": "On April 30, 2025, we held a workshop: ''Community food production through hydroponics'', aimed at seniors at the Engelwood Neighborhood Center, who learned about community food production using hydroponic techniques. We will hold continuous workshops for all ages on hydroponic food production in the community garden''s system, aiming to contribute to food sovereignty and promote education on sustainable techniques.", "es": "El 30 de abril de 2025, realizamos un taller: “Producción comunitaria de alimentos mediante la hidroponía”, dirigido a adultos mayores atendidos en el Engelwood Neighborhood Center, quienes aprendieron sobre la producción comunitaria de alimentos mediante técnicas hidropónicas, conceptos e importancia para la soberanía alimentaria. También revisaron y evaluaron el funcionamiento del sistema, los paneles de producción, el sistema de riego y el progreso de las plántulas plantadas, entre otros aspectos. Realizaremos talleres continuos para participantes de todas las edades, sobre producción hidropónica de alimentos en el sistema hidropónico del huerto comunitario. La capacitación es gratuita, y buscamos contribuir a la soberanía alimentaria en las comunidades, generando nuevas oportunidades económicas, además de promover la educación y la investigación para producir alimentos saludables utilizando técnicas sostenibles."}', 'https://biophiliaweb.org/images/actividades/20.jpeg', 3),
('activity_eco_resilience_4', 'project_eco_resilience', '2025-03-26', '{"en": "Maintenance day for the hydroponic system at Engelwood Neighborhood Center, Orlando.", "es": "Jornada de mantenimiento del sistema hidropónico del Engelwood Neighborhood Center. Orlando."}', '{"en": "On March 26 and 27, 2025, with Orlando volunteers, we evaluated and maintained the hydroponic system at the Engelwood Neighborhood Center community garden to provide community training on food production with hydroponic techniques. During the activities, the benefits of this technique were discussed, and the production panels and irrigation system were reviewed. Hydroponics allows for food production in small spaces with efficient water use, promoting sustainable food security and economic opportunities.", "es": "Con el objetivo de brindar capacitación comunitaria sobre la producción de alimentos mediante técnicas hidropónicas, el 26 y 27 de marzo de 2025, junto a voluntarios de Orlando, realizamos evaluación y mantenimiento del sistema hidropónico en el huerto comunitario del del Engelwood Neighborhood Center de Orlando. Durante las actividades, se discutieron los beneficios de producir alimentos mediante esta técnica, y al mismo tiempo, se revisaron y evaluaron los paneles de producción, el funcionamiento del sistema de riego, e iniciamos la propagación de plántulas que se utilizarán en el sistema. La hidroponía, se refiere a un sistema de cultivar en agua, donde las raíces de las plantas crecen en una solución nutritiva en lugar de en el suelo. Permite producir alimentos en espacios reducidos y con un uso eficiente del agua. Esto contribuye a promover la seguridad alimentaria sostenible, generar oportunidades económicas, fomentar la educación y la investigación."}', 'https://biophiliaweb.org/images/actividades/28.jpeg', 4),
('activity_eco_resilience_5', 'project_eco_resilience', '2025-02-24', '{"en": "Dialogue meetings on vulnerability to adverse weather events.", "es": "Encuentros de dialogo sobre la vulnerabilidad ante eventos meteorológicos adversos."}', '{"en": "On February 24 and 25, 2025, as part of our project with the Hispanic Federation, we held two pleasant citizen meetings to discuss the vulnerability of our seniors to adverse weather events. We discussed the risk factors that seniors face in their homes and communities in Orlando, Florida. We used a data collection tool that will serve as input for the Hispanic Federation to analyze and promote future projects that minimize risks for seniors.", "es": "En el marco de las acciones previstas en nuestro proyecto con Hispanic Federation, entre el 24 y 25 de febrero de 2025, desarrollamos dos agradables encuentros ciudadanos, para dialogar sobre la vulnerabilidad de nuestros adultos mayores ante eventos meteorológicos adversos. Durante el diálogo, conversamos sobre los factores de riesgo que tienen los adultos mayores en sus respectivos hogares y comunidades en Orlando, Florida. ¡Aplicamos un instrumento de recolección de datos que servirá como insumo a Hispanic Federation para analizar y promover proyectos futuros que minimicen los riesgos de adultos mayores ante eventos meteorológicos adversos! “Una persona es vulnerable cuando tiene poca o nula capacidad de protegerse frente a un riesgo”."}', 'https://biophiliaweb.org/images/actividades/32.jpeg', 5);
-- Activities for EcoPro Youth
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_ecopro_youth_1', 'project_ecopro_youth', '2025-07-16', '{"en": "Workshop: ''Heat islands and urban forest''.", "es": "Taller: ''Islas de calor y bosque urbano''."}', '{"en": "On July 16, 2025, we held the workshop ''Heat Islands and Urban Forest'' for 35 young people in Orlando, Florida, participants of the summer youth program developed by Renacer Foundation and CareerSource Central Florida. The sustainability team youths raised awareness among their peers about the consequences of high temperatures in urban environments and the role of trees as temperature regulators. They took temperature readings at different points in the Azalea Park community to analyze the causes and effects of heat islands. This activity was part of the ''Community Faith Forest'' project.", "es": "El 16 de julio 2025, realizamos el taller: ''Islas de calor y bosque urbano''. Dirigido a 35 jóvenes en la ciudad de Orlando, Florida, participantes del programa juvenil de verano, desarrollado por Renacer Foundation y CareerSource Central Florida. Durante la actividad, los jóvenes del equipo de sostenibilidad, sensibilizaron a sus compañeros sobre las consecuencias de las altas temperaturas en entornos urbanos y el rol de los árboles como reguladores de temperatura, para ello, realizaron tomas de lecturas de temperatura en diferentes puntos de la comunidad de Azalea Park, para analizar y aprender sobre las causas, consecuencias y efectos de las islas de calor en los ciudadanos y los ecosistemas. Y a su vez, conocer la importancia del dosel de los árboles, y el bosque urbano, como factores elementales en la mitigación de las islas de calor. Esta actividad se desarrolló dentro del proyecto: ''Bosque Comunitario de la Fe, un corredor ecológico urbano en Florida Central''."}', 'https://biophiliaweb.org/images/actividades/6.jpg', 1);
-- Activities for Hispanic Environmental Observatory
INSERT INTO `project_activities` (`id`, `project_id`, `date`, `title`, `description`, `imageUrl`, `display_order`) VALUES
('activity_hispanic_observatory_1', 'project_hispanic_observatory', '2025-07-05', '{"en": "Recognition from Casa Venezuela Orlando.", "es": "Reconocimiento de Casa Venezuela Orlando."}', '{"en": "On July 5, 2025, we received recognition for our work. Thanks to Casa Venezuela Orlando for this important recognition of our efforts for the Hispanic community here in the United States, as part of Venezuela''s Independence Day. It is an honor! #TheGoodGuysAreMore", "es": "El 5 de julio 2025, recibimos un reconocimiento a nuestra labor. Gracias a Casa Venezuela Orlando por este importante reconocimiento a nuestra labor en pro de la comunidad hispana acá en Estados Unidos. en el marco del Día de la Independencia de Venezuela. Es un honor! #LosBuenosSomosMas"}', 'https://biophiliaweb.org/images/actividades/7.jpg', 1),
('activity_hispanic_observatory_2', 'project_hispanic_observatory', '2025-06-11', '{"en": "''Cafecito & Connection'' sessions at Orlando Wetlands.", "es": "Jornadas de ''Cafecito & Connection en el Orlando Wetlands ''."}', '{"en": "On June 11 and 13, 2025, we participated in two ''Cafecito & Connection'' sessions organized by the Hispanic Access Foundation. On the first day, we were invited as panelists in a Virtual Round Table that brought together various non-profit organizations and project management specialists. On the second day, we met in person at Orlando Wetlands, sharing experiences and resources with various social and environmental organizations in Central Florida. Additionally, Kelley Galvis from the Florida Trail Association kindly donated 30 young explorer guides: ''My Adventure on the Florida Trail''.", "es": "El 11 y 13 de junio de 2025, participamos en dos jornadas de ''Cafecito & Connection'', organizada por Hispanic Access Foundation. Durante el primer día, fuimos invitados como panelistas en una Mesa Redonda Virtual que reunió diversas organizaciones sin fines de lucro y especialistas en la gestión de proyectos, quienes compartieron sus experiencias, perspectivas y recursos. Para el segundo día, nos reunimos de manera presencial en el Orlando Wetlands, dónde compartimos experiencias y recursos con diversas organizaciones sociales y ambientales de la Florida Central, estrechando lazos y conexiones para futuras acciones juntos. Además, realizamos una caminata por el humedal y conocimos el museo del mismo, una extraordinaria experiencia de conexión con este ecosistema. Adicionalmente, Kelley Galvis de Florida Trail Association, gentilmente nos donó 30 guias de jóvenes exploradores:''Mi aventura en el camino de Florida'', quienes la diseñaron en español junto a la  USDA y el Servicio Forestal de Florida, y que pronto utilizaremos en nuestros programas de formación ambiental."}', 'https://biophiliaweb.org/images/actividades/12.jpg', 2),
('activity_hispanic_observatory_3', 'project_hispanic_observatory', '2025-05-22', '{"en": "''II Meeting of Green Citizenship in the United States''.", "es": "''II encuentro de ciudadanía verde en los Estados Unidos''."}', '{"en": "On May 22, 2025, we participated as speakers in the ''II Meeting of Green Citizenship in the United States'', a virtual event organized by Funvive, which brought together more than 80 Venezuelan professionals dedicated to environmental management and conservation in the United States. During the event, we had the opportunity to share the experience and actions that the Biophilia Institute develops through the Hispanic Environmental Observatory in Central Florida. We thank the FUNVIVE team for the invitation!", "es": "El 22 de mayo de 2025, participamos como ponentes en el ''II encuentro de ciudadanía verde en los Estados Unidos'', un evento virtual organizado por Funvive,  que reunió a más de 80 Venezolanos profesionales dedicados a la gestión y conservación ambiental en Estados Unidos. Durante la actividad, tuvimos la oportunidad de dar a conocer la experiencia y acciones que desarrolla Biophilia Institute a través del Observatorio Ambiental Hispano en la Florida Central. Agradecemos al equipo de FUNVIVE por la invitación!"}', 'https://biophiliaweb.org/images/actividades/17.jpg', 3),
('activity_hispanic_observatory_4', 'project_hispanic_observatory', '2025-05-26', '{"en": "''II Community Day Familia Day 2025''.", "es": "''II jornada comunitaria Familia Day 2025''."}', '{"en": "On May 26, 2025, in Orlando, we participated in the #FamiliaDay 2025 community event, organized by Renacer Foundation. Through our information table, we raised awareness among participants about the effects of extreme heat, how to grow vegetables at home, medicinal plant recipes, and gave away seeds. It was a wonderful day with great participation and joy for our #Hispanic community. Thanks to Renacer Foundation for this invitation!", "es": "El 26 de mayo de 2025, en la ciudad de Orlando, participamos en la jornada comunitaria #FamiliaDay 2025. Organizada por Renacer  Foundation. Durante la actividad, la Dra. Mónica Vargas de Fundacion Crecemos Todos, dió una conferencia sobre ''oportunidades universitarias para jóvenes'', enmarcada en el proyecto ''Senderos a la ciencia'', que desarrolla Hispanic Access Foundation junto a Renacer Foundation. Además, diferentes organizaciones brindaron servicios gratuitos a los participantes en el área de salud, educación y ambiente, se entregaron bolsas de comida e insumos para mujeres embarazadas. A traves de nuestra mesa informativa, sensibilizamos a los participantes sobre los efectos del calor extremo, como sembrar hortalizas en casa a través de macetas, recetas de plantas medicinales, entregamos semillas, orientamos sobre la importancia de los árboles en la ciudad, y regalamos dos plantas de tomate ya produciendo. Fue un día maravilloso, con mucha participación y alegría para nuestra comunidad #hispana Gracias a Renacer Foundation por esta invitación!"}', 'https://biophiliaweb.org/images/actividades/18.jpeg', 4),
('activity_hispanic_observatory_5', 'project_hispanic_observatory', '2025-04-23', '{"en": "''Panel on Renewable Energies and Environment''.", "es": "“Panel sobre Energías Renovables y Medioambiente”."}', '{"en": "On Wednesday, April 23, 2025, we were invited to be part of the ''Panel on Renewable Energies and Environment'', organized by Florida Puerto Rican Parade, Inc., as part of the #EarthMonth celebrations. During the event, we discussed the importance of developing clean energy programs in communities to contribute to sustainability and the role of Hispanic participation as a key element in this process. It was an honor to share the panel with Rafa Almonte, Carrie Black, Orlyn Itriago, Alejandro Florez, and the excellent moderation of Luis Martinez.", "es": "El miércoles 23 de abril de 2025, fuimos invitados a formar parte del “Panel sobre Energías Renovables y Medioambiente”, organizado por Florida Puerto Rican Parade, Inc. En el marco de las celebraciones del #EarthMonth. Durante la actividad, dialogamos sobre la importancia del desarrollo de programas de energías limpias en comunidades para contribuir a la sostenibilidad, sobre el rol de la participación hispana como elemento clave en este proceso, y además, conocimos las diferentes iniciativas de organizaciones panelistas para contribuir al desarrollo sostenible de las ciudades, en especial en la Florida Central. Fue un honor para nosotros compartir el panel con Rafa Almonte, Carrie Black, Orlyn Itriago, Alejandro Florez, y la excelente moderación de Luis Martinez. Agradecemos a Soraya Márquez por las amables gestiones e incorporación."}', 'https://biophiliaweb.org/images/actividades/23.jpeg', 5),
('activity_hispanic_observatory_6', 'project_hispanic_observatory', '2025-04-22', '{"en": "''Cleanup day at the nature center and habitat restoration in Apopka''.", "es": "”Jornada de limpieza del centro natural y de restauración del hábitat en Apopka”."}', '{"en": "On April 22, 2025, celebrating Earth Day, we joined the Orange Audubon Society for a cleanup day to create the nature center and habitat restoration area at the Apopka Birding Park. During the activity, we performed various tasks, from cleaning and removing debris from the old nursery to removing invasive plants from a beautiful oak tree. We thank the Orange Audubon family for the invitation and hope to continue supporting the consolidation of their nature center project.", "es": "El 22 de abril de 2025, en el marco de la celebración del Earth Day, nos unimos a Orange Audubon Society en una jornada de limpieza para la creación del centro natural y área de restauración del hábitat en el Parque de Observación de Aves de Apopka, ubicado aledaño al Sendero de Vida Silvestre del Lago Apopka. Durante la actividad, realizamos varias actividades, desde limpiar, botar escombros del antigüo vivero y hasta retirar plantas invasoras de una hermoso roble. Agradecemos a la familia Orange Audubon por la invitación y esperamos seguir apoyando en la consolidación de su proyecto del centro natural."}', 'https://biophiliaweb.org/images/actividades/24.jpeg', 6),
('activity_hispanic_observatory_7', 'project_hispanic_observatory', '2025-03-12', '{"en": "''Climate Correction 2025 Annual Conference, Orlando''.", "es": "“Conferencia anual Climate Correction 2025, Orlando”."}', '{"en": "On March 12 and 13, 2025, at the Celeste Hotel in Orlando, Florida, we participated in the ''Climate Correction 2025'' conference, an annual conference organized by the VoLo Foundation. This year''s theme was ''Leaders in Action'', where individuals, communities, and leading organizations in innovation and climate resilience gathered to share experiences and update knowledge on the current climate reality. The event featured various workshops, conferences, art exhibitions, and technology related to the environmental theme and climate change. We thank the VoLo Foundation team for the excellent organization and annual initiative to highlight the issue of climate change in Florida.", "es": "El 12 y 13 de marzo de 2025, en el Hotel Celeste en la ciudad de Orlando. Florida, participamos en la conferencia ''Climate Correction 2025'', una conferencia organizada todos los años por VoLo Foundation. El tema de este año fue ''Líderes en Acción'', donde personas, comunidades y organizaciones líderes en innovación y resiliencia climática nos reunimos para compartir experiencias y actualizar conocimientos sobre la realidad climática actual. Durante la actividad, se desarrollaron diversos talleres, conferencias, exposiciones de arte y tecnología vinculadas al tema ambiental y el cambio climático. Agradecemos al equipo de VoLo Foundation por la excelente organización e iniciativa anual para realzar el tema de cambio climático en la Florida."}', 'https://biophiliaweb.org/images/actividades/29.jpeg', 7);

-- 6. TEAM MEMBERS
INSERT INTO `team_members` (`id`, `name`, `role`, `bio`, `imageUrl`, `imageAlt`, `display_order`) VALUES
('team_faruk', '{"en": "FARUK BAGDAH", "es": "FARUK BAGDAH"}', '{"en": "President/CEO", "es": "Presidente/CEO"}', '{"en": "Sanford, FL.", "es": "Sanford, FL."}', 'https://biophiliaweb.org/images/team/Faruk Bagdah.png', 'Photo of FARUK BAGDAH', 1),
('team_victor', '{"en": "VICTOR MARTINEZ", "es": "VICTOR MARTINEZ"}', '{"en": "Director/Advisor", "es": "Director/Asesor"}', '{"en": "New Smyrna, FL.", "es": "New Smyrna, FL."}', 'https://biophiliaweb.org/images/team/Victor Martínez.jpg', 'Photo of VICTOR MARTINEZ', 2),
('team_oliver', '{"en": "OLIVER SANRONA", "es": "OLIVER SANRONA"}', '{"en": "Director/Advisor", "es": "Director/Asesor"}', '{"en": "Houston, TX.", "es": "Houston, TX."}', 'https://biophiliaweb.org/images/team/Oliver Sangona.jpg', 'Photo of OLIVER SANRONA', 3),
('team_giuseppe', '{"en": "GIUSEPPE BERARDI", "es": "GIUSEPPE BERARDI"}', '{"en": "Director/Advisor", "es": "Director/Asesor"}', '{"en": "Big Lake, MN.", "es": "Big Lake, MN."}', 'https://biophiliaweb.org/images/team/Giuseppe Berardi.jpg', 'Photo of GIUSEPPE BERARDI', 4),
('team_simon', '{"en": "SIMON TENORIO", "es": "SIMON TENORIO"}', '{"en": "Director/Advisor", "es": "Director/Asesor"}', '{"en": "Apopka, FL.", "es": "Apopka, FL."}', 'https://biophiliaweb.org/images/team/Simon Tenorio.jpg', 'Photo of SIMON TENORIO', 5);

-- 7. BLOG POSTS
-- The blog is currently empty, so no inserts are needed for the `blog_posts` table.